eureka:
  server:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname:localhost}:${eureka.server.port:8762}/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

info:
  me: https://github.com/marvinwjs/learningcloud.git